export const FETCH_LIST_PRODUCT="FETCH_LIST_PRODUCT";
export const SET_LIST_PRODUCT="SET_LIST_PRODUCT";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"